defaults: &defaults
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['db_name'] || 'rails' %>
  pool: 5
  username: <%= ENV['db_username'] || 'postgres' %>
  password: <%= ENV['db_password'] || 'password' %>
  host: <%= ENV['db_host'] || 'localhost' %>
  port: <%= ENV['db_port'] || '5432' %>

development:
  <<: *defaults

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *defaults
