---
- hosts: 127.0.0.1

  vars:

    rails_app_home: $app_home/app

    app_name: rails
    project_name: project
    enviroment_name: environment
    new_relic_key: ""
    new_relic_monitoring_mode: false


  vars_files:
    - env.yaml


  tasks:

  - name: "Setup new relic"
    action: template src=newrelic.yml dest=$rails_app_home/config/newrelic.yml

  - name: "Install app dependencies"
    action: yum name=${item}
    with_items:
    - sqlite-devel
    - memcached

  - name: Start memcache service
    action: service name=memcached state=started

  - name: Database migrate
    action: 'shell su -l -c "cd ${rails_app_home}; source ${app_name}.env; export db_password db_port db_name db_host db_username; rake db:migrate" ${app_name}'

  - name: Install nginx
    action: yum name=nginx

  - name: Configure nginx
    action: template src=nginx-default.conf dest=/etc/nginx/conf.d/default.conf
    notify:
    - restart nginx

  - name: Ensure nginx is running
    action: service name=nginx state=started

  handlers:
  - name: restart nginx
    action: service name=nginx state=restarted
