---
- hosts: 127.0.0.1

  vars:

    rails_app_home: $app_home/app

    APP_NAME: rails
    NEW_RELIC_KEY: ""
    NEW_RELIC_MONITORING_MODE: false


  vars_files:
    - env.yaml


  tasks:

  - name: "Setup new relic"
    action: template src=newrelic.yml dest=$rails_app_home/config/newrelic.yml

  - name: "Install app dependencies"
    action: yum name=sqlite-devel

  - name: Install nginx
    action: yum name=nginx

  - name: Configure nginx
    action: template src=nginx-default.conf dest=/etc/nginx/conf.d/default.conf
    notify:
    - restart nginx

  - name: Ensure nginx is running
    action: service name=nginx state=started


  handlers:
  - name: restart nginx
    action: service name=nginx state=restarted
